# Generated by Django 4.0.6 on 2022-07-10 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='글 제목')),
                ('description', models.TextField(verbose_name='글 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='글 작성 시간')),
                ('category', models.CharField(max_length=20, verbose_name='분류')),
                ('price', models.CharField(max_length=20, verbose_name='가격')),
                ('process_status', models.CharField(max_length=2, verbose_name='상태')),
                ('writer', models.ForeignKey(db_column='writer', on_delete=django.db.models.deletion.CASCADE, related_name='board', to='accounts.user', verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Board_comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('board_id', models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.board')),
                ('comment_id', models.ForeignKey(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='board.board_comments')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='accounts.user')),
            ],
        ),
    ]
