# Generated by Django 4.0.6 on 2022-07-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('board_id', models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.board')),
                ('comment_id', models.ForeignKey(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='board.board_comments')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writers', to='accounts.user')),
            ],
        ),
    ]
