# Generated by Django 4.0.6 on 2022-07-09 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('board', '0002_board_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_comments',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='accounts.user'),
        ),
    ]
