# Generated by Django 3.2.14 on 2022-07-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_comments_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='process_status',
            field=models.CharField(max_length=20, verbose_name='상태'),
        ),
    ]
